(function(){
'use strict';
const VERSION='1.0.0-CON-RC';
const STORE='melec_full_data';
const AUDIT='deltatracker_audit_v1';
const META='deltatracker_meta_v1';
const COVER='deltatracker_coverage_v1';
const CURRICULUM={"version":"2026-09-02","provenance":{"maths":"Synthèse Drive Programmes_Mathematiques_College_Lycee.md — référentiels EN, à conserver avec ses dates d'application.","sciences_college_lycee":"Source officielle détaillée non identifiée de façon suffisamment fiable dans le Drive pendant cette passe : couverture laissée vide plutôt que complétée par supposition.","melec":"Thèmes de la banque MELEC actuellement intégrée à DeltaTracker (codes MAT/SCI), utilisés pour le pilotage de couverture. Ne remplace pas le texte officiel du BO."},"tracks":{"college":{"label":"Collège","levels":{"6e":{"maths":["Nombres, calculs et résolution de problèmes","Grandeurs et mesures","Espace et géométrie","Organisation et gestion de données et probabilités","Proportionnalité","Pensée informatique"]},"5e":{"maths":["Nombres relatifs","Fractions","Puissances carré et cube","Calcul littéral et équations simples","Repérage et géométrie","Statistiques et probabilités","Proportionnalité et fonctions","Pensée informatique"]},"4e":{"maths":["Nombres relatifs : multiplication et division","Fractions : opérations complètes","Puissances","Racine carrée","Équations du premier degré","Pythagore","Statistiques","Probabilités","Proportionnalité","Pensée informatique"]},"3e":{"maths":["Fractions irréductibles","Puissances et notation scientifique","Équations produit nul","Inéquations","Identités remarquables","Thalès","Trigonométrie","Vecteurs","Statistiques et probabilités","Fonctions linéaires et affines","Fonction carré","Pensée informatique"]}}},"lycee":{"label":"Lycée","levels":{"2de":{"maths":["Analyse : fonctions et variations","Géométrie : vecteurs et repérage","Statistiques et probabilités","Algorithmique et programmation Python","Logique et raisonnement"]},"1re":{"maths":["Algèbre et analyse : suites, fonctions, dérivation","Géométrie","Statistiques et probabilités","Algorithmique et programmation"]},"Tle":{"maths":["Analyse : limites, continuité, dérivation, intégration","Suites numériques","Géométrie dans l'espace","Probabilités conditionnelles","Algorithmique avancée"]}}},"melec":{"label":"Bac Pro MELEC","levels":{"1MELEC":{"maths":[],"sciences":[]},"TMELEC":{"maths":["Calcul numérique et notation scientifique","Fonctions et lecture graphique","Suites numériques","Dérivation et variations","Trigonométrie et signaux","Statistiques à une variable","Statistiques à deux variables et ajustement","Probabilités"],"sciences":["Tension alternative et signaux","Puissance électrique et facteur de puissance","Réseaux triphasés et couplages","Machine asynchrone","Diodes, redressement et filtrage","Sécurité électrique et protections","Énergie électrique","Mesures électriques et multimètre"]}}},"bts":{"label":"BTS Électrotechnique","levels":{"BTS1":{"maths":[]},"BTS2":{"maths":[]}}}}};

function $(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toLowerCase()}
function sig(s){return norm(s).split(' ').filter(Boolean).sort().join('|')}
function cleanName(s){return String(s||'').replace(/\u00a0/g,' ').trim().replace(/^\s*\d{1,3}\s*[.\-):]?\s+(?=[A-Za-zÀ-ÿ])/,'').replace(/\s+/g,' ').trim()}
function tracker(){return window.__tracker||null}
function getData(){const t=tracker(); if(t&&t.data)return t.data; try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return {}}}
function saveAndRender(){const t=tracker(); if(t){t.save();t.render();} else localStorage.setItem(STORE,JSON.stringify(getData()))}
function readAudit(){try{return JSON.parse(localStorage.getItem(AUDIT)||'[]')}catch(e){return[]}}
function audit(type,detail){const a=readAudit();a.unshift({ts:new Date().toISOString(),type,detail:detail||{}});localStorage.setItem(AUDIT,JSON.stringify(a.slice(0,300)));renderAudit()}
function toast(msg,bad){const t=tracker();if(t&&t.toast){t.toast(msg,bad?'warning':'success');return}const n=document.createElement('div');n.textContent=msg;n.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:100000;background:'+(bad?'#991b1b':'#174f8f')+';color:#fff;padding:12px 16px;border-radius:12px;font:600 14px system-ui';document.body.appendChild(n);setTimeout(()=>n.remove(),3200)}
function randomSafeId(){const a=new Uint8Array(8);if(window.crypto&&crypto.getRandomValues)crypto.getRandomValues(a);else for(let i=0;i<a.length;i++)a[i]=Math.floor(Math.random()*256);return 'E-'+Array.from(a).map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
function inferMeta(s){
  const c=String(s.class||'').trim().toUpperCase();
  if(!s.track){if(/MELEC/.test(c))s.track='MELEC';else if(/BTS/.test(c))s.track='BTS Électrotechnique';else if(/(^|\s)(6E|5E|4E|3E)(\s|$)/.test(c))s.track='Collège';else if(/(2DE|SECONDE|1RE|PREMIERE|PREMIÈRE|TLE|TERMINALE)/.test(c))s.track='Lycée';}
  if(!s.level){if(/(TMELEC|TER\s*MELEC|TERMINALE.*MELEC)/.test(c))s.level='Terminale Bac Pro';else if(/(^|\s)3E(\s|$)/.test(c))s.level='3e';else if(/(^|\s)4E(\s|$)/.test(c))s.level='4e';else if(/(^|\s)5E(\s|$)/.test(c))s.level='5e';else if(/(^|\s)6E(\s|$)/.test(c))s.level='6e';else if(/2DE|SECONDE/.test(c))s.level='Seconde';else if(/1RE|PREMIERE|PREMIÈRE/.test(c))s.level='Première';else if(/TLE|TERMINALE/.test(c))s.level='Terminale';}
  if(!Array.isArray(s.subjects)||!s.subjects.length){if(s.track==='MELEC')s.subjects=['maths','sciences'];}
  if(!s.safeId)s.safeId=randomSafeId();
  return s;
}
function migrate(){const d=getData();if(!Array.isArray(d.students))return;let changed=0;d.students.forEach(s=>{const before=JSON.stringify([s.name,s.track,s.level,s.subjects,s.safeId]);s.name=cleanName(s.name);inferMeta(s);if(before!==JSON.stringify([s.name,s.track,s.level,s.subjects,s.safeId]))changed++;});if(changed){saveAndRender();audit('MIGRATION_CONSOLIDATED',{students:d.students.length,recordsUpdated:changed})}}

function ensureStyle(){if($('dtStyle'))return;const s=document.createElement('style');s.id='dtStyle';s.textContent=`
.dt-card{border:1px solid #d9e2ef;border-radius:13px;padding:14px;margin:12px 0;background:#fff}.dt-card h3{margin:0 0 5px;font-size:16px}.dt-muted{color:#5b6576;font-size:13px}
.dt-btn{border:2px solid #20589b;background:#20589b;color:#fff;border-radius:11px;padding:10px 14px;font-weight:700;cursor:pointer}.dt-btn.alt{background:#fff;color:#174f8f}
.dt-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.dt-field label{display:block;font-size:12px;margin-bottom:4px}.dt-field input,.dt-field select,.dt-field textarea{box-sizing:border-box;width:100%;border:1px solid #c8d3e1;border-radius:9px;padding:10px;font:14px system-ui;background:#fff}
.dt-checks{display:flex;gap:14px;flex-wrap:wrap;padding:8px 0}.dt-lock{background:#eef6ff;border-left:4px solid #20589b;padding:9px 11px;border-radius:7px;font-size:12px;margin-top:8px}.dt-danger{color:#b91c1c;font-weight:700}.dt-ok{color:#166534;font-weight:700}
#dtImportModal{position:fixed;inset:0;background:#0008;display:none;align-items:center;justify-content:center;z-index:99999;padding:14px}#dtImportModal .dt-modal{background:#fff;width:min(650px,96vw);max-height:92vh;overflow:auto;border-radius:16px;padding:18px}
.dt-audit-row{padding:8px 0;border-bottom:1px solid #eef1f5;font-size:12px}.dt-coverage-row{display:grid;grid-template-columns:minmax(160px,1fr) auto;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid #eef1f5}.dt-stage button{border:1px solid #cbd5e1;background:#fff;border-radius:7px;padding:5px 7px;margin-left:3px;cursor:pointer}.dt-stage button.on{background:#20589b;color:#fff;border-color:#20589b}
`;document.head.appendChild(s)}
function ensureModal(){if($('dtImportModal'))return;const m=document.createElement('div');m.id='dtImportModal';m.innerHTML=`<div class="dt-modal"><h2 style="margin:0 0 12px">Importer une section</h2><div class="dt-grid"><div class="dt-field"><label>Univers *</label><select id="dtTrack"><option value="">— Choisir —</option><option>Collège</option><option>Lycée</option><option>MELEC</option><option>BTS Électrotechnique</option></select></div><div class="dt-field"><label>Niveau *</label><select id="dtLevel"><option value="">— Choisir d'abord l'univers —</option></select></div><div class="dt-field"><label>Groupe / classe *</label><input id="dtGroup" placeholder="Ex. 3e A, TMELEC C"></div></div><div class="dt-field" style="margin-top:10px"><label>Matières *</label><div class="dt-checks"><label><input type="checkbox" id="dtMath" checked> Mathématiques</label><label><input type="checkbox" id="dtSci"> Physique-chimie / Sciences physiques</label></div></div><div class="dt-field"><label>Liste à importer *</label><textarea id="dtList" rows="9" placeholder="Prénom Nom — une ligne par élève&#10;ou collez un CSV"></textarea></div><div class="dt-lock">🔒 Données nominatives locales uniquement — jamais GitHub / jamais IA externe. Les exports SAFE remplacent les identités par des pseudonymes stables.</div><div id="dtImportPreview" style="margin:10px 0;font-size:13px"></div><div style="display:flex;gap:10px"><button class="dt-btn" id="dtDoImport">Importer</button><button class="dt-btn alt" id="dtCancelImport">Annuler</button></div></div>`;document.body.appendChild(m);
  $('dtTrack').onchange=updateLevels;$('dtDoImport').onclick=doImport;$('dtCancelImport').onclick=()=>m.style.display='none';['dtTrack','dtLevel','dtGroup','dtList','dtMath','dtSci'].forEach(id=>{const e=$(id);e.addEventListener('input',()=>$('dtImportPreview').innerHTML='');e.addEventListener('change',()=>$('dtImportPreview').innerHTML='')})
}
function updateLevels(){const t=$('dtTrack').value;let levels=[];if(t==='Collège')levels=['6e','5e','4e','3e'];else if(t==='Lycée')levels=['Seconde','Première','Terminale'];else if(t==='MELEC')levels=['Seconde Bac Pro','Première Bac Pro','Terminale Bac Pro'];else if(t==='BTS Électrotechnique')levels=['BTS 1re année','BTS 2e année'];$('dtLevel').innerHTML='<option value="">— Choisir —</option>'+levels.map(x=>'<option>'+esc(x)+'</option>').join('')}
function parseNames(txt){const out=[];String(txt||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const p=line.split(/[;,|\t]/).map(x=>x.trim()).filter(Boolean);const n=cleanName(p.length>=2?p[0]+' '+p[1]:line);if(!/^(pr[eé]nom\s+nom|nom\s+pr[eé]nom|nom|pr[eé]nom)$/i.test(n)&&n)out.push(n)});return out}
function openImport(){ensureModal();$('dtImportModal').style.display='flex'}
function doImport(){const track=$('dtTrack').value.trim(),level=$('dtLevel').value.trim(),group=$('dtGroup').value.trim(),maths=$('dtMath').checked,sci=$('dtSci').checked,names=parseNames($('dtList').value);const errors=[];if(!track)errors.push('univers');if(!level)errors.push('niveau');if(!group)errors.push('groupe / classe');if(!maths&&!sci)errors.push('matière');if(!names.length)errors.push('liste d’élèves');if(errors.length){$('dtImportPreview').innerHTML='<span class="dt-danger">Import bloqué : '+esc(errors.join(', '))+' requis.</span>';return}
  const fileSeen=new Set(),unique=[];let dupFile=0;names.forEach(n=>{const k=sig(n);if(fileSeen.has(k))dupFile++;else{fileSeen.add(k);unique.push(n)}});const d=getData();d.students=Array.isArray(d.students)?d.students:[];const existing=new Set(d.students.filter(s=>norm(s.class)===norm(group)).map(s=>sig(s.name)));const blocked=unique.filter(n=>existing.has(sig(n)));if(blocked.length){$('dtImportPreview').innerHTML='<span class="dt-danger">Import bloqué : '+blocked.length+' doublon(s) détecté(s) dans '+esc(group)+', même si nom/prénom sont inversés.</span><br>'+blocked.map(esc).join(', ');return}
  if(!confirm(unique.length+' élève(s) seront ajoutés à « '+group+' » ('+level+'). Continuer ?'))return;unique.forEach(n=>d.students.push({id:'dt_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9),name:n,class:group,track,level,subjects:[maths?'maths':null,sci?'sciences':null].filter(Boolean),safeId:randomSafeId()}));saveAndRender();audit('IMPORT_SECTION',{group,track,level,count:unique.length,totalDetected:names.length,duplicatesInFile:dupFile});$('dtImportModal').style.display='none';toast(unique.length+' élève(s) importé(s) dans '+group+'.')
}

function sanitize(v,map){if(Array.isArray(v))return v.map(x=>sanitize(x,map));if(v&&typeof v==='object'){const o={};Object.keys(v).forEach(k=>{if(/^(name|studentName|firstName|lastName|prenom|prénom|nom|safeId)$/i.test(k))return;let x=v[k];if(/studentId/i.test(k)&&typeof x==='string')x=map[x]||'UNKNOWN';o[k]=sanitize(x,map)});return o}return v}
function downloadJson(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),700)}
function exportSafe(){migrate();const d=getData(),students=Array.isArray(d.students)?d.students:[],map={};students.forEach(s=>{if(!s.safeId)s.safeId=randomSafeId();map[s.id]=s.safeId});saveAndRender();const safe={exportType:'DeltaTracker SAFE',version:VERSION,createdAt:new Date().toISOString(),privacy:{identitiesIncluded:false,stablePseudonyms:true,localOnlyMapping:true},students:students.map(s=>({id:s.safeId,class:s.class||'',track:s.track||'',level:s.level||'',subjects:Array.isArray(s.subjects)?s.subjects:[]})),observations:sanitize(Array.isArray(d.observations)?d.observations:[],map)};downloadJson(safe,'DeltaTracker_SAFE_'+new Date().toISOString().slice(0,10)+'.json');audit('EXPORT_SAFE',{students:safe.students.length,observations:safe.observations.length,stablePseudonyms:true})}
function backupComplete(){const payload={type:'DeltaTracker Backup Local',version:VERSION,createdAt:new Date().toISOString(),data:getData(),audit:readAudit(),coverage:readCoverage()};downloadJson(payload,'DeltaTracker_BACKUP_COMPLET_'+new Date().toISOString().replace(/[:.]/g,'-')+'.json');audit('BACKUP_LOCAL',{students:(payload.data.students||[]).length})}
function restoreComplete(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files&&input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);if(!obj||!obj.data||!Array.isArray(obj.data.students))throw new Error('Sauvegarde DeltaTracker non reconnue.');if(!confirm('Restaurer cette sauvegarde locale ? Les données actuelles seront remplacées.'))return;localStorage.setItem(STORE,JSON.stringify(obj.data));if(Array.isArray(obj.audit))localStorage.setItem(AUDIT,JSON.stringify(obj.audit));if(obj.coverage)localStorage.setItem(COVER,JSON.stringify(obj.coverage));location.reload()}catch(e){alert('Restauration impossible : '+e.message)}};r.readAsText(f,'utf-8')};input.click()}

function readCoverage(){try{return JSON.parse(localStorage.getItem(COVER)||'{}')}catch(e){return{}}}
function saveCoverage(c){localStorage.setItem(COVER,JSON.stringify(c))}
function trackKey(s){if(s.track==='Collège')return'college';if(s.track==='Lycée')return'lycee';if(s.track==='MELEC')return'melec';if(s.track==='BTS Électrotechnique')return'bts';return''}
function levelKey(s){const t=trackKey(s),l=s.level||'';if(t==='college')return l;if(t==='lycee')return l==='Seconde'?'2de':l==='Première'?'1re':l==='Terminale'?'Tle':'';if(t==='melec')return /Terminale/.test(l)?'TMELEC':/Première/.test(l)?'1MELEC':'';if(t==='bts')return /2/.test(l)?'BTS2':'BTS1';return''}
function topicsFor(s,subject){const tk=trackKey(s),lk=levelKey(s);try{return CURRICULUM.tracks[tk].levels[lk][subject]||[]}catch(e){return[]}}
function covKey(id,subject,topic){return id+'|'+subject+'|'+topic}
function setStage(id,subject,topic,stage){const c=readCoverage();c[covKey(id,subject,topic)]=stage;saveCoverage(c);renderCoverage()}
function renderCoverage(){const sel=$('dtCovStudent'),sub=$('dtCovSubject'),box=$('dtCovRows'),summary=$('dtCovSummary');if(!sel||!sub||!box)return;const d=getData(),s=(d.students||[]).find(x=>x.id===sel.value);if(!s){box.innerHTML='<div class="dt-muted">Sélectionnez un élève.</div>';return}const subjects=(s.subjects&&s.subjects.length?s.subjects:['maths']);sub.innerHTML=subjects.map(x=>'<option value="'+esc(x)+'">'+(x==='maths'?'Mathématiques':'Sciences')+'</option>').join('');if(!subjects.includes(sub.value))sub.value=subjects[0];const topics=topicsFor(s,sub.value),c=readCoverage();if(!topics.length){box.innerHTML='<div class="dt-muted">Référentiel détaillé non chargé pour ce profil. DeltaTracker n’invente pas les notions manquantes.</div>';summary.textContent='';return}let total=0;box.innerHTML=topics.map(topic=>{const st=Number(c[covKey(s.id,sub.value,topic)]||0);total+=st;return '<div class="dt-coverage-row"><span>'+esc(topic)+'</span><span class="dt-stage"><button data-st="1" class="'+(st>=1?'on':'')+'">Vu</button><button data-st="2" class="'+(st>=2?'on':'')+'">Entraîné</button><button data-st="3" class="'+(st>=3?'on':'')+'">Évalué</button></span></div>'}).join('');box.querySelectorAll('button').forEach((b,i)=>{b.onclick=()=>{const row=Math.floor(i/3),stage=Number(b.dataset.st);setStage(s.id,sub.value,topics[row],stage)}});summary.textContent='Couverture : '+Math.round(total/(topics.length*3)*100)+' % — '+topics.length+' notion(s)';}
function installCoverageCard(card){card.innerHTML='<h3>📚 Couverture programme / suivi individuel</h3><div class="dt-muted">Suivi local en 3 étapes : Vu → Entraîné → Évalué. Les notions proviennent uniquement du référentiel chargé.</div><div class="dt-grid" style="margin-top:10px"><div class="dt-field"><label>Élève</label><select id="dtCovStudent"></select></div><div class="dt-field"><label>Matière</label><select id="dtCovSubject"></select></div></div><div id="dtCovSummary" class="dt-muted" style="margin:8px 0"></div><div id="dtCovRows"></div>';const d=getData();$('dtCovStudent').innerHTML='<option value="">— Choisir —</option>'+(d.students||[]).slice().sort((a,b)=>a.name.localeCompare(b.name,'fr')).map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+' — '+esc(s.class||'sans classe')+'</option>').join('');$('dtCovStudent').onchange=renderCoverage;$('dtCovSubject').onchange=renderCoverage;renderCoverage()}

function renderAudit(){const box=$('dtAuditRows');if(!box)return;const a=readAudit().slice(0,12);box.innerHTML=a.length?a.map(x=>'<div class="dt-audit-row"><b>'+esc(x.type)+'</b> <span class="dt-muted">'+new Date(x.ts).toLocaleString('fr-FR')+'</span><br><code>'+esc(JSON.stringify(x.detail||{}))+'</code></div>').join(''):'<div class="dt-muted">Aucune action enregistrée.</div>'}
function makeCard(id,title,desc,html){const d=document.createElement('div');d.id=id;d.className='dt-card';d.innerHTML='<h3>'+title+'</h3><div class="dt-muted">'+desc+'</div>'+html;return d}
function installUI(){ensureStyle();ensureModal();const cp=$('tabClass');if(cp&&!$('dtClassTools')){const c=makeCard('dtClassTools','👥 Gestion des classes et élèves','Import sécurisé, contrôle des doublons et données locales uniquement.','<div style="margin-top:10px"><button class="dt-btn" id="dtOpenImport">➕ Ajouter / importer une section</button></div>');const target=Array.from(cp.children).find(x=>/ÉLÈVES\s*\/\s*APPRENTIS/i.test(x.textContent||''));target?cp.insertBefore(c,target):cp.appendChild(c);$('dtOpenImport').onclick=openImport}
  const dp=$('tabDashboard');if(dp){let anchor=Array.from(dp.children).find(x=>/DONNÉES\s*\(SAUVEGARDE\)/i.test(x.textContent||''));function after(node){anchor&&anchor.parentNode?anchor.parentNode.insertBefore(node,anchor.nextSibling):dp.appendChild(node);anchor=node}
    if(!$('dtFirewallCard'))after(makeCard('dtFirewallCard','🛡️ Data Firewall','Export SAFE : pseudonymes stables, aucune identité, métadonnées pédagogiques conservées.','<div style="margin-top:10px"><button class="dt-btn" id="dtExportSafe">Export SAFE</button></div>'));if($('dtExportSafe'))$('dtExportSafe').onclick=exportSafe;
    if(!$('dtBackupCard'))after(makeCard('dtBackupCard','💾 Sauvegarde complète','Sauvegarde locale nominative à conserver hors GitHub.','<div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:10px"><button class="dt-btn" id="dtBackupComplete">Backup complet</button><button class="dt-btn alt" id="dtRestoreComplete">Restaurer</button></div>'));if($('dtBackupComplete'))$('dtBackupComplete').onclick=backupComplete;if($('dtRestoreComplete'))$('dtRestoreComplete').onclick=restoreComplete;
    if(!$('dtCoverageCard')){const c=document.createElement('div');c.id='dtCoverageCard';c.className='dt-card';after(c);installCoverageCard(c)}
    if(!$('dtAuditCard'))after(makeCard('dtAuditCard','🧾 Journal d’audit local','Historique local des opérations sensibles, sans identité d’élève.','<div id="dtAuditRows" style="margin-top:8px"></div>'));renderAudit();
  }
}
function selfTest(){const results=[];function ok(name,v){results.push({name,ok:!!v})};ok('tracker disponible',!!tracker());ok('clé data lisible',!!getData());ok('curriculum collège 3e',topicsFor({track:'Collège',level:'3e'},'maths').length>0);ok('signature nom/prénom inversé',sig('TEST Alpha')===sig('Alpha TEST'));const s={class:'TMELEC A',track:'',level:'',subjects:[]};inferMeta(s);ok('inférence MELEC',s.track==='MELEC'&&s.level==='Terminale Bac Pro');console.table(results);return results}
function boot(){migrate();installUI();setTimeout(()=>{installUI();renderAudit()},300);window.DeltaTracker={version:VERSION,exportSafe,backupComplete,restoreComplete,selfTest,curriculum:CURRICULUM};console.log('[DeltaTracker '+VERSION+'] moteur consolidé actif');selfTest()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
